- project:
    check:
      jobs:
        - ansible-test-sanity
        - ansible-role-tests-2.5-py2
        - ansible-role-tests-2.5-py3
    gate:
      jobs:
        - ansible-test-sanity
        - ansible-role-tests-2.5-py2
        - ansible-role-tests-2.5-py3
